apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-qradar-config
  namespace: ibm-techxchange-lab
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type json
      </parse>
    </source>

    <match **>
      @type remote_syslog
      host 192.168.210.227
      port 514
      protocol udp
      program falco-fluentd
      severity debug
      facility user
      <buffer>
      </buffer>
      <format>
        @type single_value
        message_key message
      </format>
    </match>